### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by taewonkang** [LymanSong/FP_GNN#3]
Hey,

I read your paper and wanted to test the code, but the error occurs-

I tried to do the test run, and train_test.py code runs fine.
But when I run test_code.py code subsequently,
![capture](https://user-images.githubusercontent.com/29134153/135227255-51a2feaa-794b-4428-af4c-980e1609dcbc.PNG)
This happens.

Guess it is a simple problem, but I cannot handle since I dunno where to init 'device'...
Can you help me out?

**Comment by LymanSong** [comment]
Hi there.
First of all, thank you for paying attention to my works!

Unlike train_test.py, test_code.py has __main__ and that means it run by itself. And if you see the line 119,
`device = torch.device("cuda:" + str(args.device)) if torch.cuda.is_available() else torch.device("cpu")` takes device argument(variable) automatically. 
It assigns 'cpu' to the variable if you don't have any CUDA GPU, 'cuda:0' otherwise.([check this](https://pytorch.org/docs/stable/tensor_attributes.html?highlight=device#torch.torch.device)) It is just nothing but the tensor processor you are gonna use. And Tensors in ~~GNN functions must know which device you are gonna use later (so that they can be stored in the right place). This is why functions takes 'device' argument. I guess you missed 'device' variable before get in to test function in line 125. You better check it before go in to 'test' function.

Hope I helped.

**Comment by LymanSong** [comment]
Hi there. 

I added 'device' argument to DWGNN model in line 60

I can't test it on my desktop now, so please rerun your code and tell me if error occurs again.

Thank you for paying attention to my works!

Hope it helps.

**Comment by taewonkang** [comment]
Thanks, it works now :)
